# Generated by Django 4.1.7 on 2023-06-09 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        (
            "app_order",
            "0002_image_review_specification_subcategories_tag_sales_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="available",
            field=models.BooleanField(default=True, verbose_name="В продаже"),
        ),
        migrations.AddField(
            model_name="product",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Создан"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="fabricator",
            field=models.CharField(
                default="", max_length=100, verbose_name="Производитель"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="limited",
            field=models.BooleanField(default=False, verbose_name="Ограниченная серия"),
        ),
        migrations.AddField(
            model_name="product",
            name="model",
            field=models.CharField(default="", max_length=100, verbose_name="Модель"),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                default="", max_length=255, unique=True, verbose_name="URL товара"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=0, verbose_name="В наличии"),
        ),
        migrations.AddField(
            model_name="product",
            name="type_device",
            field=models.CharField(
                default="", max_length=50, verbose_name="Тип устройства"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Цена"
            ),
        ),
    ]
