# Generated by Django 4.1.7 on 2023-06-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(verbose_name="order number")),
                ("account", models.IntegerField(verbose_name="account number")),
            ],
            options={
                "verbose_name": "payment request",
                "verbose_name_plural": "requests",
                "db_table": "payments",
            },
        ),
    ]
